# Generated by Django 6.0.3 on 2026-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('entreprise', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('participants', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
