# Generated by Django 6.0.3 on 2026-04-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=20)),
                ('certification', models.CharField(default='Certifié', max_length=100)),
            ],
        ),
    ]
