# Generated by Django 6.0.3 on 2026-04-15 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='certificat',
            field=models.FileField(blank=True, null=True, upload_to='certificats/'),
        ),
        migrations.AddField(
            model_name='client',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formation'),
        ),
        migrations.AddField(
            model_name='client',
            name='progression',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cours_pdf/')),
                ('ordre', models.IntegerField(default=1)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.formation')),
            ],
        ),
    ]
