# Generated by Django 6.0.3 on 2026-04-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_certificat_client_formation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='video_url',
            new_name='lien_video',
        ),
        migrations.RemoveField(
            model_name='client',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='module',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='module',
            name='pdf',
        ),
        migrations.AddField(
            model_name='client',
            name='formations',
            field=models.ManyToManyField(blank=True, to='core.formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='modules/'),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz')], default='video', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='code_acces',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('termine', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField(auto_now_add=True)),
                ('code_certificat', models.CharField(max_length=20, unique=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse_correcte', models.CharField(max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module')),
            ],
        ),
    ]
