# Generated by Django 6.0.3 on 2026-04-10 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('code_acces', models.CharField(default=uuid.uuid4, max_length=10, unique=True)),
            ],
        ),
    ]
