# Generated by Django 6.0.3 on 2026-04-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='formateur',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='prix',
        ),
        migrations.AddField(
            model_name='formation',
            name='certification',
            field=models.CharField(default='Certifié', max_length=100),
        ),
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(default='Pas de description'),
        ),
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(default='Pas de description', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
